version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: absense-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: absense
    volumes:
      - absense_pg_data_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: absense-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: absense-backend-prod
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/absense
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads

volumes:
  absense_pg_data_prod:
