"""support_multiple_lecturers_and_programmes

Revision ID: 0acfdf11bc04
Revises: f8a9b0c1d2e3
Create Date: 2026-03-05 15:00:46.230284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acfdf11bc04'
down_revision: Union[str, None] = 'f8a9b0c1d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_lecturers',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'lecturer_id')
    )
    op.create_table('course_programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('programme', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_programmes_course_id'), 'course_programmes', ['course_id'], unique=False)
    op.drop_constraint('courses_lecturer_id_fkey', 'courses', type_='foreignkey')
    op.drop_column('courses', 'lecturer_id')
    op.drop_column('courses', 'programme')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('programme', sa.VARCHAR(length=100), server_default=sa.text("'General'::character varying"), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('lecturer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('courses_lecturer_id_fkey', 'courses', 'users', ['lecturer_id'], ['id'])
    op.drop_index(op.f('ix_course_programmes_course_id'), table_name='course_programmes')
    op.drop_table('course_programmes')
    op.drop_table('course_lecturers')
    # ### end Alembic commands ###
