"""add_level_programme_to_users_and_courses

Revision ID: be2442e8c93f
Revises: a1b2c3d4e5f6
Create Date: 2026-02-22 01:07:51.837162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2442e8c93f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('level', sa.Integer(), server_default='100', nullable=False))
    op.add_column('courses', sa.Column('programme', sa.String(length=100), server_default='General', nullable=False))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('programme', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'programme')
    op.drop_column('users', 'level')
    op.drop_column('courses', 'programme')
    op.drop_column('courses', 'level')
    # ### end Alembic commands ###
