"""add_notes_to_verification_log

Revision ID: d6794ae76994
Revises: db87d8d4d5b7
Create Date: 2025-10-18 08:55:51.381816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6794ae76994'
down_revision: Union[str, None] = 'db87d8d4d5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_logs', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_logs', 'notes')
    # ### end Alembic commands ###
