"""user face ref

Revision ID: ca0a3d693094
Revises: d10df2908aad
Create Date: 2025-10-02 14:53:07.746291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0a3d693094'
down_revision: Union[str, None] = 'd10df2908aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_reference_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face_reference_path')
    # ### end Alembic commands ###
